export const OPTIONS = [
  {
    label: 'House',
    value: 1,
    id_sell: 1,
    id_rent:12,
    icon: '/assets/images/new_publish/publish/casa.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Apartament',
    value: 2,
    id_sell: 2,
    id_rent:13,
    icon: '/assets/images/new_publish/publish/apartamento.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Office',
    value: 3,
    id_sell: 3,
    id_rent:14,
    icon: '/assets/images/new_publish/publish/office.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Land',
    value: 4,
    id_sell: 4,
    id_rent:15,
    icon: '/assets/images/new_publish/publish/proyecto.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Comercial spaces',
    value: 5,
    id_sell: 5,
    id_rent:16,
    icon: '/assets/images/new_publish/publish/tienda.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Parking',
    value: 6,
    id_sell: 6,
    id_rent:17,
    icon: '/assets/images/new_publish/publish/garaje.svg',
    enable: [1, 2],
  },
  {
    label: 'Warehouse',
    value: 7,
    id_sell: 7,
    id_rent:18,
    icon: '/assets/images/new_publish/publish/almacen.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Chalet',
    value: 8,
    id_sell: 8,
    id_rent:19,
    icon: '/assets/images/new_publish/publish/chalet.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Medical space',
    value: 9,
    id_sell: 9,
    id_rent:20,
    icon: '/assets/images/new_publish/publish/hospital.svg',
    enable: [1, 2, 4],
  },
  {
    label: 'Tiny house',
    value: 10,
    id_sell: 10,
    id_rent:21,
    icon: '/assets/images/new_publish/publish/tiny.svg',
    enable: [1, 2],
  },
  {
    label: 'Rent a room',
    value: 11,
    id_sell: null,
    id_rent:null,
    icon: '/assets/images/new_publish/publish/rent-a-room.svg',
    enable: [3],
  },
  {
    label: 'Shared office',
    value: 12,
    id_sell: null,
    id_rent:null,
    icon: '/assets/images/new_publish/publish/office.svg',
    enable: [3],
  },
  {
    label: 'Coworking place',
    value: 13,
    id_sell: null,
    id_rent:null,
    icon: '/assets/images/new_publish/publish/coworking-place.svg',
    enable: [3],
  },
  {
    label: 'Other',
    value: 14,
    icon: '',
    id_sell: 11,
    id_rent:22,
    enable: [1, 2, 4],
  },

];

